### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kesshijordan** [kesshijordan/messyversionclusterviz#3]
@jyeatman since this inherited from your AFQ-viz, how should I handle the licensing and is there somewhere I should acknowledge you/the AFQ-viz? Thanks! -Kesshi

**Comment by jyeatman** [comment]
good question @arokem do you know?

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://brainandeducation.com

**Comment by arokem** [comment]
Hi - so sorry - this somehow flew by me earlier.

I think this is the answer:

http://softwareengineering.stackexchange.com/questions/277688/if-i-fork-a-project-on-github-that-is-licensed-under-mit-how-to-i-handle-the-at

For example, in dipy, we carry around the scikit-image license in some
parts of the code, because we lifted some of their code for our purposes:

https://github.com/nipy/dipy/blob/master/dipy/segment/mask.py#L164-L191

**Comment by kesshijordan** [comment]
I migrated this over to, what I think, is the cleaner way to do it. https://github.com/kesshijordan/Cluster-viz

**Comment by kesshijordan** [comment]
@arokem I followed the license link you sent (using the new repo, see link)... the license for the AFQ-viz had the University of Washington, not yeatmanlab, so I put that. @jyeatman is that okay or should I put you, by name?

https://github.com/kesshijordan/Cluster-viz/blob/master/LICENSE.txt

Thanks!
Kesshi
